[package]
name = "finplan_core"
version = "0.1.0"
edition = "2024"

[dependencies]
jiff = { workspace = true }
serde = { workspace = true }

ts-rs = { workspace = true, optional = true }

rand = "0.9.2"
rand_distr = "0.5.1"
rayon = "1.11.0"

[features]
ts = ["ts-rs"]
