# Configuration for WASM builds

[target.wasm32-unknown-unknown]
rustflags = [
    '--cfg', 'getrandom_backend="wasm_js"',
    '--cfg=web_sys_unstable_apis',
    '-C', 'target-feature=+reference-types,+bulk-memory',

]
