[package]
name = "finplan"
version = "0.1.0"
edition = "2024"

[dependencies]
jiff = { version = "0.2.16", features = ["serde"] }
rand = "0.9.2"
rand_distr = "0.5.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
